### ISSUE TITLE
Crash when trying to open a block's UI on server (1.16.1 - v1.1.0)

### ISSUE THREAD

**Issue by ghost** [MCrafterzz/VanillaAutomated#6]
LibGui 2.1.1+1.16.1 is present but not installed separately.

https://pastebin.com/HumdgHrU

**Comment by MarcusElg** [comment]
I will look into it. Haven't seen that error before 🤔

**Comment by MarcusElg** [comment]
This is the line which crashes:
`WItemSprite item = new WItemSprite(new ItemStack(Registry.ITEM.get(new Identifier(itemStrings[i + j * 3].replace(".", ":"))), 1));`

Using the fabric discord bot class I get this: net/minecraft/class_4597 => net/minecraft/client/render/VertexConsumerProvider

I find this very strange because I don't do anything with something like that. Looking at the line it must be WItemSprite that's causing it but noone else has had this error so this makes me suspect that it's a mod conflict. Looking at your mod list the most suspectable is Exotic Blocks, that feels like the only one which would mixin to rendering. So if you could try it without that mod and see if it's the same result then it would be great!

**Comment by ghost** [comment]
I created a brand new server in a separate directory to test with Fabric 0.9.0-build.204.
The same error happens: https://pastebin.com/Wss8RPAt
I also include the full server log: https://pastebin.com/GxRu62Mc

The world folder was deleted before starting the server.

On a side note, a lot of errors are shown when cotton resources isn't present.  Though it's not listed as a dependency.

If you're developing on windows, could the reason be related to me being on linux?  Something like case sensitivity?

**Comment by MarcusElg** [comment]
The cotton resources errors is due to there being no way to control the json files from code, just ignore them they don't affect anything 🤷‍♂️ 

Your issue is probably due to it being on a server. I will test that myself.

**Comment by MarcusElg** [comment]
Can confirm it only happens on servers:
java.lang.RuntimeException: Cannot load class net.minecraft.client.render.VertexConsumerProvider in environment type SERVER

Edit: I've found the cause to the issue, now I just need to fix it :P

**Comment by ghost** [comment]
That's great!  Thank you for your efforts :-D

**Comment by MarcusElg** [comment]
1.1.1 fixes the issue. Thanks for reporting, and thanks for using my mod!

**Comment by ghost** [comment]
Thanks!  I'm looking forward to exploring more of it. :-D
